In [ ]:
# Creacion de dataset
import os
import shutil
import random

# Directorio de origen que contiene imágenes y archivos de texto
source_dir = "/home/farix/python/dataset/imagenesTotalesPng"

# Directorio de destino para las imágenes y archivos de texto seleccionados
destination_dir_selected = "/home/farix/python/dataset/imagenesTotalesPngTrain"

# Directorio de destino para las imágenes y archivos de texto no seleccionados
destination_dir_remaining = "ruta/a/tu/directorio/carpeta_restanteVal"

# Crear directorios de destino si no existen
os.makedirs(destination_dir_selected, exist_ok=True)
os.makedirs(destination_dir_remaining, exist_ok=True)

# Lista de archivos de imágenes en el directorio de origen
image_files = [file for file in os.listdir(source_dir) if file.endswith((".jpg", ".png", ".jpeg", ".bmp"))]

# Seleccionar aleatoriamente 300 imágenes
selected_images = random.sample(image_files, min(300, len(image_files)))

# Copiar las imágenes seleccionadas y sus archivos de texto correspondientes
for image in selected_images:
    source_image_path = os.path.join(source_dir, image)
    destination_image_path = os.path.join(destination_dir_selected, image)
    shutil.copy(source_image_path, destination_image_path)

    # Comprobar si hay un archivo de texto correspondiente
    text_file = os.path.splitext(image)[0] + ".txt"
    if text_file in image_files:
        source_text_path = os.path.join(source_dir, text_file)
        destination_text_path = os.path.join(destination_dir_selected, text_file)
        shutil.copy(source_text_path, destination_text_path)

# Copiar las imágenes y archivos de texto no seleccionados a la carpeta de destino restante
for image in image_files:
    if image not in selected_images:
        source_image_path = os.path.join(source_dir, image)
        destination_image_path = os.path.join(destination_dir_remaining, image)
        shutil.copy(source_image_path, destination_image_path)

        # Comprobar si hay un archivo de texto correspondiente
        text_file = os.path.splitext(image)[0] + ".txt"
        if text_file in image_files:
            source_text_path = os.path.join(source_dir, text_file)
            destination_text_path = os.path.join(destination_dir_remaining, text_file)
            shutil.copy(source_text_path, destination_text_path)

print("Proceso completado.")


In [ ]:
# Ordenar para entrenamiento
import os
import shutil
import random

# Directorio de origen que contiene imágenes y archivos de texto
source_dir = "/home/farix/python/dataset/imagenesTotalesPng"

# Directorio de destino para las imágenes y archivos de texto seleccionados
destination_dir_selected = "/home/farix/python/dataset/imagenesTotalesPngTrain"

# Directorio de destino para las imágenes no seleccionadas
destination_dir_remaining = "/home/farix/python/dataset/imagenesTotalesPngVal"

# Crear directorio de destino si no existe
os.makedirs(destination_dir_selected, exist_ok=True)
os.makedirs(destination_dir_remaining, exist_ok=True)

# Lista de archivos de imágenes en el directorio de origen
image_files = [file for file in os.listdir(source_dir) if file.endswith((".jpg", ".png", ".jpeg", ".bmp"))]

# Crear una lista de tuplas (nombre de imagen, nombre de archivo de texto)
image_text_pairs = [(image, image.replace(".png", ".txt")) for image in image_files]

# Seleccionar aleatoriamente 300 imágenes
selected_image_text_pairs = random.sample(image_text_pairs, min(312, len(image_files)))

# Copiar las imágenes seleccionadas y sus archivos de texto correspondientes (si existen)
for image, text_file in selected_image_text_pairs:
    source_image_path = os.path.join(source_dir, image)
    destination_image_path = os.path.join(destination_dir_selected, image)
    source_text_path = os.path.join(source_dir, text_file)
    
    if os.path.exists(source_text_path):
        destination_text_path = os.path.join(destination_dir_selected, text_file)
        shutil.copy(source_text_path, destination_text_path)
    
    shutil.copy(source_image_path, destination_image_path)

# Copiar las imágenes no seleccionadas a la carpeta de destino restante
for image, text_file in image_text_pairs:
    if (image, text_file) not in selected_image_text_pairs:
        source_image_path = os.path.join(source_dir, image)
        destination_image_path = os.path.join(destination_dir_remaining, image)
        source_text_path = os.path.join(source_dir, text_file)
        
        if os.path.exists(source_text_path):
            destination_text_path = os.path.join(destination_dir_remaining, text_file)
            shutil.copy(source_text_path, destination_text_path)
        
        shutil.copy(source_image_path, destination_image_path)

print("Proceso completado.")


In [43]:
import cv2
import os

# Cargar la imagen TIFF en formato BGR con OpenCV
img_path = '/home/farix/python/imagenesTiffSinNir/IMG_PER1_20220127_block_1_1.tif'
im1 = cv2.imread(img_path, cv2.IMREAD_UNCHANGED)  # OpenCV image

# Obtener las dimensiones de la imagen original
height, width = im1.shape[:2]

# Dividir la imagen en 4 bloques
block1 = im1[:height//2, :width//2]
block2 = im1[:height//2, width//2:]
block3 = im1[height//2:, :width//2]
block4 = im1[height//2:, width//2:]

# Carpeta donde guardar los bloques
output_folder = '/home/farix/python/dataTest/miniBloquesTIff'
os.makedirs(output_folder, exist_ok=True)

# Guardar los bloques con el mismo nombre más número de bloque
cv2.imwrite(os.path.join(output_folder, 'block1.tif'), block1)
cv2.imwrite(os.path.join(output_folder, 'block2.tif'), block2)
cv2.imwrite(os.path.join(output_folder, 'block3.tif'), block3)
cv2.imwrite(os.path.join(output_folder, 'block4.tif'), block4)


True

In [40]:
import cv2

# Ruta del archivo TIFF
# tiff_file_path = '/home/farix/python/dataset/imagenesTotalesTiff32/IMG_PER1_20170121_block_1_1_block_0_0.tif'
# tiff_file_path = '/home/farix/python/dataset/imagenesTotalesTiff/IMG_PER1_20170121_block_1_1_block_0_0.tif'
# tiff_file_path = '/home/farix/python/preprocesamiento/imagen_convertidav2.tif'
tiff_file_path = '/home/farix/python/dataset/imagenesTotalesTiffSinNIR/IMG_PER1_20170121_block_1_1_block_0_0.tif'

# Abre el archivo TIFF con OpenCV
image = cv2.imread(tiff_file_path, cv2.IMREAD_UNCHANGED)
print(image)
# if image is not None:
#     # Realiza operaciones con la imagen aquí
#     # Por ejemplo, mostrar la imagen
#     cv2.imshow('Imagen TIFF', image)
#     cv2.waitKey(0)  # Espera hasta que se presione una tecla (puede cerrar la ventana de la imagen)

#     # Cierra la ventana de la imagen y libera recursos
#     cv2.destroyAllWindows()
# else:
#     print(f'No se pudo abrir la imagen en {tiff_file_path}')


[[[598 425 340]
  [590 421 335]
  [607 438 346]
  ...
  [598 447 358]
  [610 457 366]
  [604 451 364]]

 [[605 434 342]
  [587 426 334]
  [595 434 339]
  ...
  [621 461 370]
  [605 449 360]
  [607 450 363]]

 [[599 435 336]
  [577 425 327]
  [590 436 337]
  ...
  [621 456 367]
  [613 452 362]
  [614 454 365]]

 ...

 [[612 456 365]
  [620 463 371]
  [627 467 375]
  ...
  [646 468 382]
  [662 481 393]
  [633 463 377]]

 [[631 472 380]
  [727 546 442]
  [747 563 454]
  ...
  [627 459 374]
  [643 470 384]
  [631 465 380]]

 [[673 508 410]
  [793 600 486]
  [712 540 436]
  ...
  [615 452 368]
  [621 456 372]
  [612 453 369]]]


In [38]:
import cv2

# Ruta del archivo TIFF
tiff_file_path = '/home/farix/python/dataset/imagenesTotalesTiff/IMG_PER1_20170121_block_1_1_block_0_0.tif'

# Intenta abrir el archivo TIFF con OpenCV
# image = cv2.imread(tiff_file_path)
# image = cv2.imread(tiff_file_path, cv2.IMREAD_UNCHANGED)
image = cv2.imread(tiff_file_path, -1)


# Verifica si la apertura fue exitosa
if image is not None:
    # Puedes realizar operaciones con la imagen aquí
    # Por ejemplo, mostrar la imagen
    cv2.imshow('Imagen', image)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
else:
    print(f"No se pudo abrir la imagen en {tiff_file_path}")


In [37]:
from PIL import Image
import numpy
# Ruta del archivo TIFF
# tiff_file_path = '/home/farix/python/dataset/imagenesTotalesTiff/IMG_PER1_20170121_block_1_1_block_0_0.tif'
# tiff_file_path = '/home/farix/python/dataset/imagenesTotalesTiff32/IMG_PER1_20170121_block_1_1_block_0_0.tif'
tiff_file_path='/home/farix/python/dataset/imagenesTotalesTiff/IMG_PER1_20170121_block_1_1_block_0_0.tif'
# Abre el archivo TIFF
image = Image.open(tiff_file_path)
image_array = numpy.array(image)
# print(image)

# Imprime los valores de los píxeles
print(image_array)

# Puedes realizar operaciones con la imagen aquí
# Por ejemplo, mostrar la imagen
# image.show()

# # Cierra la imagen después de terminar de trabajar con ella
# image.close()


[[[1 1 2 0]
  [1 1 2 0]
  [1 1 2 0]
  ...
  [1 1 2 0]
  [1 1 2 0]
  [1 1 2 0]]

 [[1 1 2 0]
  [1 1 2 0]
  [1 1 2 0]
  ...
  [1 1 2 0]
  [1 1 2 0]
  [1 1 2 0]]

 [[1 1 2 0]
  [1 1 2 0]
  [1 1 2 0]
  ...
  [1 1 2 0]
  [1 1 2 0]
  [1 1 2 0]]

 ...

 [[1 1 2 0]
  [1 1 2 1]
  [1 1 2 1]
  ...
  [1 1 2 1]
  [1 1 2 1]
  [1 1 2 1]]

 [[1 1 2 1]
  [1 2 2 1]
  [1 2 2 1]
  ...
  [1 1 2 1]
  [1 1 2 1]
  [1 1 2 1]]

 [[1 1 2 1]
  [1 2 3 1]
  [1 2 2 1]
  ...
  [1 1 2 0]
  [1 1 2 0]
  [1 1 2 0]]]
